/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package radiotest;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author tonyc
 */
public class Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());
    
    private JPanel cardPanel;
    private CardLayout cardLayout;
    
    private Panel panel;
    private Nepal nepal;
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);
        
        panel = new Panel();
        nepal = new Nepal();
        
        cardPanel.add(panel, "Panel");
        cardPanel.add(nepal, "Nepal");
        
        setLayout(new BorderLayout());
        add(cardPanel, BorderLayout.CENTER);
    }
    
    public final void showPanel(String panelName) {
        cardLayout.show(cardPanel, panelName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Optionmnb = new javax.swing.JMenu();
        Panelitm = new javax.swing.JMenuItem();
        Nepalitm = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Optionmnb.setText("Option");

        Panelitm.setText("Panel");
        Panelitm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelitmActionPerformed(evt);
            }
        });
        Optionmnb.add(Panelitm);

        Nepalitm.setText("Nepal");
        Nepalitm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NepalitmActionPerformed(evt);
            }
        });
        Optionmnb.add(Nepalitm);

        jMenuItem2.setText("jMenuItem2");
        Optionmnb.add(jMenuItem2);

        jMenuBar1.add(Optionmnb);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelitmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelitmActionPerformed
        showPanel("Panel");
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelitmActionPerformed

    private void NepalitmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NepalitmActionPerformed
        showPanel("Nepal");
        // TODO add your handling code here:
    }//GEN-LAST:event_NepalitmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Nepalitm;
    private javax.swing.JMenu Optionmnb;
    private javax.swing.JMenuItem Panelitm;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
