package university;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tonyc
 */
public class Registro_Prof extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registro_Prof.class.getName());

    /**
     * Creates new form Registro_Prof
     */
    public Registro_Prof() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        titlelbl = new javax.swing.JLabel();
        IDlbl = new javax.swing.JLabel();
        Maillbl = new javax.swing.JLabel();
        Namelbl = new javax.swing.JLabel();
        Explbl = new javax.swing.JLabel();
        Splbl = new javax.swing.JLabel();
        IDtxf = new javax.swing.JTextField();
        Mailtxf = new javax.swing.JTextField();
        Exptxf = new javax.swing.JTextField();
        Sptxf = new javax.swing.JTextField();
        Agregbtn = new javax.swing.JButton();
        Nametxf = new javax.swing.JTextField();

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titlelbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        titlelbl.setForeground(new java.awt.Color(51, 153, 0));
        titlelbl.setText("SISTEMA DE REGISTRO DE DOCENTES");

        IDlbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        IDlbl.setText("Identificacion:");

        Maillbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        Maillbl.setText("Email:");

        Namelbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        Namelbl.setText("Nombre:");

        Explbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        Explbl.setText("Años de experiencia:");

        Splbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        Splbl.setText("Especialidad:");

        IDtxf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDtxfActionPerformed(evt);
            }
        });

        Mailtxf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailtxfActionPerformed(evt);
            }
        });

        Exptxf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExptxfActionPerformed(evt);
            }
        });

        Sptxf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SptxfActionPerformed(evt);
            }
        });

        Agregbtn.setBackground(new java.awt.Color(204, 255, 204));
        Agregbtn.setText("AGREGAR");
        Agregbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Agregbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregbtnActionPerformed(evt);
            }
        });

        Nametxf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NametxfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titlelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Splbl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Sptxf, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Explbl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Exptxf, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Maillbl, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Mailtxf, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(IDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(64, 64, 64))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(Namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(101, 101, 101)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Nametxf, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IDtxf, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(Agregbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(titlelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nametxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDtxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Maillbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mailtxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Explbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exptxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Splbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sptxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(Agregbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDtxfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDtxfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDtxfActionPerformed

    private void MailtxfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailtxfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MailtxfActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void ExptxfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExptxfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExptxfActionPerformed

    private void SptxfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SptxfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SptxfActionPerformed

    private void AgregbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregbtnActionPerformed
        try {
            String nombre = Nametxf.getText().trim();
            String id = IDtxf.getText().trim();
            String mail = Mailtxf.getText().trim();
            String exp = Exptxf.getText().trim();
            String sp = Sptxf.getText().trim();
            if (nombre.isEmpty() || id.isEmpty() || mail.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nombre, ID y Email son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int añosExp = 0;
            if (!exp.isEmpty()) {
                try {
                    añosExp = Integer.parseInt(exp);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Años de experiencia debe ser un número", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            Profesor nuevoProfesor = new Profesor(nombre, id, mail, añosExp, sp);

            JOptionPane.showMessageDialog(this, """
                                                Profesor agregado exitosamente:
                                                Nombre: """ + nuevoProfesor.getNombre() + 
                "\n", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            Nametxf.setText("");
            IDtxf.setText("");
            Mailtxf.setText("");
            Exptxf.setText("");
            Sptxf.setText("");
            Nametxf.requestFocus();
            
            } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al agregar profesor: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        
    }
    }//GEN-LAST:event_AgregbtnActionPerformed

    private void NametxfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NametxfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NametxfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registro_Prof().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregbtn;
    private javax.swing.JLabel Explbl;
    private javax.swing.JTextField Exptxf;
    private javax.swing.JLabel IDlbl;
    private javax.swing.JTextField IDtxf;
    private javax.swing.JLabel Maillbl;
    private javax.swing.JTextField Mailtxf;
    private javax.swing.JLabel Namelbl;
    private javax.swing.JTextField Nametxf;
    private javax.swing.JLabel Splbl;
    private javax.swing.JTextField Sptxf;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel titlelbl;
    // End of variables declaration//GEN-END:variables
}
