/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package radioemisor;

import javax.swing.*;

/**
 *
 * @author tonyc
 */
public class CrearRadioPanel extends javax.swing.JPanel {
    private final RadioEmisor radio;
    private final MainWindow mainWindow;
    /**
     * Creates new form CrearRadioPanel
     * @param radio
     * @param mainWindow
     */
    public CrearRadioPanel(RadioEmisor radio, MainWindow mainWindow) {
        this.radio = radio;
        this.mainWindow = mainWindow;
        initComponents();
    }
    
    private void crearRadio() {
        try {
            String nombre = nombreField.getText().trim();
            double frecuencia = Double.parseDouble(frecuenciaField.getText().trim());
            String direccionWeb = direccionWebField.getText().trim();
            
            if (nombre.isEmpty() || direccionWeb.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos los campos son requeridos", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            radio.setNombre(nombre);
            radio.setFrecuencia(frecuencia);
            radio.setDireccionWeb(direccionWeb);
            
            JOptionPane.showMessageDialog(this, "Radioemisora creada exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            mainWindow.setRadio(radio);
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "La frecuencia debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreField = new javax.swing.JTextField();
        frecuenciaField = new javax.swing.JTextField();
        direccionWebField = new javax.swing.JTextField();
        RdNamelbl = new javax.swing.JLabel();
        RdFreqlbl = new javax.swing.JLabel();
        RdDirecclbl = new javax.swing.JLabel();
        crearButton = new javax.swing.JButton();
        CrearRdlbl = new javax.swing.JLabel();

        nombreField.setOpaque(true);

        frecuenciaField.setOpaque(true);
        frecuenciaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frecuenciaFieldActionPerformed(evt);
            }
        });

        direccionWebField.setOpaque(true);

        RdNamelbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        RdNamelbl.setText("Nombre:");

        RdFreqlbl.setFont(RdFreqlbl.getFont().deriveFont(RdFreqlbl.getFont().getSize()+2f));
        RdFreqlbl.setText("Frecuencia:");

        RdDirecclbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        RdDirecclbl.setText("Direccion Web:");

        crearButton.setBackground(new java.awt.Color(204, 255, 255));
        crearButton.setText("Crear Radioemisora");
        crearButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        crearButton.setOpaque(true);
        crearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearButtonActionPerformed(evt);
            }
        });

        CrearRdlbl.setBackground(new java.awt.Color(102, 102, 0));
        CrearRdlbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        CrearRdlbl.setText("Crear Radioemisora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RdNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RdFreqlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RdDirecclbl)
                            .addComponent(crearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CrearRdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(frecuenciaField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(direccionWebField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(311, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(CrearRdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RdNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frecuenciaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RdFreqlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionWebField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RdDirecclbl))
                .addGap(18, 18, 18)
                .addComponent(crearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void frecuenciaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frecuenciaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frecuenciaFieldActionPerformed

    private void crearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearButtonActionPerformed
        crearRadio();
    }//GEN-LAST:event_crearButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CrearRdlbl;
    private javax.swing.JLabel RdDirecclbl;
    private javax.swing.JLabel RdFreqlbl;
    private javax.swing.JLabel RdNamelbl;
    private javax.swing.JButton crearButton;
    private javax.swing.JTextField direccionWebField;
    private javax.swing.JTextField frecuenciaField;
    private javax.swing.JTextField nombreField;
    // End of variables declaration//GEN-END:variables
}
