/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package radioemisor;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author tonyc
 */
public class LocutoresPanel extends javax.swing.JPanel {
    private RadioEmisor radio;
    /**
     * Creates new form LocutoresPanel
     * @param radio
     */
    public LocutoresPanel(RadioEmisor radio) {
        this.radio = radio;
        JScrollPane scrollPane = new JScrollPane(locutoresArea);
        add(scrollPane, BorderLayout.CENTER);
        initComponents();
    }
    
    public void setRadio(RadioEmisor radio) {
        this.radio = radio;
    }
    
    private void agregarLocutor() {
        if (!radio.isCreada()) {
            JOptionPane.showMessageDialog(this, "Primero debe crear la radioemisora", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            int id = Integer.parseInt(idField.getText().trim());
            String nombre = nombreField.getText().trim();
            String correo = correoField.getText().trim();
            String telefono = telefonoField.getText().trim();
            
            if (nombre.isEmpty() || correo.isEmpty() || telefono.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos los campos son requeridos", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Locutor locutor = new Locutor(id, nombre, correo, telefono);
            radio.addLocutor(locutor);
            
            // Limpiar campos
            idField.setText("");
            nombreField.setText("");
            correoField.setText("");
            telefonoField.setText("");
            
            actualizarDatos();
            JOptionPane.showMessageDialog(this, "Locutor agregado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void actualizarDatos() {
        if (!radio.isCreada()) {
            locutoresArea.setText("Primero debe crear la radioemisora");
            return;
        }
        
        java.util.List<Locutor> locutores = radio.getLocutores();
        if (locutores.isEmpty()) {
            locutoresArea.setText("No hay locutores registrados");
            return;
        }
        
        StringBuilder sb = new StringBuilder("Locutores registrados:\n\n");
        for (Locutor locutor : locutores) {
            sb.append("ID: ").append(locutor.getIdentificador())
              .append(", Nombre: ").append(locutor.getNombre())
              .append(", Correo: ").append(locutor.getCorreo())
              .append(", Teléfono: ").append(locutor.getTelefono())
              .append("\n");
        }
        
        locutoresArea.setText(sb.toString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegLoclbl = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        correoField = new javax.swing.JTextField();
        telefonoField = new javax.swing.JTextField();
        LocNamelbl = new javax.swing.JLabel();
        LocIDlbl = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        locutoresArea = new javax.swing.JTextArea();
        LocMaillbl = new javax.swing.JLabel();
        LocTellbl = new javax.swing.JLabel();
        agregarButton = new javax.swing.JButton();

        RegLoclbl.setBackground(new java.awt.Color(102, 102, 0));
        RegLoclbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        RegLoclbl.setText("Registrar Locutores");

        nombreField.setOpaque(true);

        correoField.setOpaque(true);
        correoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoFieldActionPerformed(evt);
            }
        });

        telefonoField.setOpaque(true);

        LocNamelbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        LocNamelbl.setText("Nombre:");

        LocIDlbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        LocIDlbl.setText("ID:");

        idField.setOpaque(true);

        locutoresArea.setEditable(false);
        locutoresArea.setColumns(20);
        locutoresArea.setRows(5);
        jScrollPane1.setViewportView(locutoresArea);

        LocMaillbl.setFont(LocMaillbl.getFont().deriveFont(LocMaillbl.getFont().getSize()+2f));
        LocMaillbl.setText("Correo:");

        LocTellbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        LocTellbl.setText("Telefono:");

        agregarButton.setBackground(new java.awt.Color(204, 255, 255));
        agregarButton.setText("Agregar Locutor");
        agregarButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        agregarButton.setOpaque(true);
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegLoclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LocTellbl)
                                    .addComponent(LocNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LocMaillbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LocIDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(correoField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telefonoField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 273, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(agregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RegLoclbl)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocIDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(correoField)
                    .addComponent(LocMaillbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocTellbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void correoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoFieldActionPerformed

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        agregarLocutor();
    }//GEN-LAST:event_agregarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LocIDlbl;
    private javax.swing.JLabel LocMaillbl;
    private javax.swing.JLabel LocNamelbl;
    private javax.swing.JLabel LocTellbl;
    private javax.swing.JLabel RegLoclbl;
    private javax.swing.JButton agregarButton;
    private javax.swing.JTextField correoField;
    private javax.swing.JTextField idField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea locutoresArea;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField telefonoField;
    // End of variables declaration//GEN-END:variables
}
