/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package radioemisor;

import javax.swing.*;
import java.awt.*;
/**
 *
 * @author tonyc
 */
public class MainWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());
    private RadioEmisor radio;
    private final JPanel cardPanel;
    private final CardLayout cardLayout;

    // Paneles
    private CrearRadioPanel crearRadioPanel;
    private LocutoresPanel locutoresPanel;
    private ProgramasPanel programasPanel;
    private DiscosPanel discosPanel;
    private PlaylistPanel playlistPanel;
    private ConsultasPanel consultasPanel;
    private ProgramasListPanel programasListPanel;
    
    /**
     * Creates new form RadioApp
     */
    
    public MainWindow() {
        initComponents();
        // Inicializar la radio (vacía al principio)
        radio = new RadioEmisor("", 0, "");
        
        // Crear el panel de cards
        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);
        
        // Crear los paneles
        crearRadioPanel = new CrearRadioPanel(radio, this);
        locutoresPanel = new LocutoresPanel(radio);
        programasPanel = new ProgramasPanel(radio);
        discosPanel = new DiscosPanel(radio);
        playlistPanel = new PlaylistPanel(radio);
        consultasPanel = new ConsultasPanel(radio);
        programasListPanel = new ProgramasListPanel(radio);
        
        // Agregar paneles al cardPanel
        cardPanel.add(crearRadioPanel, "CrearRadio");
        cardPanel.add(locutoresPanel, "Locutores");
        cardPanel.add(programasPanel, "Programas");
        cardPanel.add(discosPanel, "Discos");
        cardPanel.add(playlistPanel, "Playlist");
        cardPanel.add(consultasPanel, "Consultas");
        cardPanel.add(programasListPanel, "ListarProgramas");
        
        setLayout(new BorderLayout());
        add(cardPanel, BorderLayout.CENTER);
    }
    
    
    /**
     * Muestra el panel especificado
     * @param panelName Nombre del panel a mostrar
     */
    public final void showPanel(String panelName) {
        cardLayout.show(cardPanel, panelName);
        
        // Actualizar datos en los paneles si es necesario
        switch (panelName) {
            case "Locutores":
                locutoresPanel.actualizarDatos();
                break;
            /*case "Programas":
                programasPanel.actualizarDatos();
                break;
            case "Discos":
                discosPanel.actualizarDatos();
                break;
            case "Playlist":
                playlistPanel.actualizarDatos();
                break;
            case "Consultas":
                consultasPanel.actualizarDatos();
                break;
            case "ListarProgramas":
                programasListPanel.actualizarDatos();
                break;*/
            default:
                break;
        }
    }
    
    /**
     * Actualiza la referencia a la radioemisora después de crearla
     * @param radio La radioemisora creada
     */
    public void setRadio(RadioEmisor radio) {
        this.radio = radio;
        // Actualizar la referencia en todos los paneles
        locutoresPanel.setRadio(radio);
        /*programasPanel.setRadio(radio);
        discosPanel.setRadio(radio);
        playlistPanel.setRadio(radio);
        consultasPanel.setRadio(radio);
        programasListPanel.setRadio(radio);*/
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuBar = new javax.swing.JMenuBar();
        OpcMenu = new javax.swing.JMenu();
        crearRadioItem = new javax.swing.JMenuItem();
        locutoresItem = new javax.swing.JMenuItem();
        programasItem = new javax.swing.JMenuItem();
        discosItem = new javax.swing.JMenuItem();
        playlistItem = new javax.swing.JMenuItem();
        consultasItem = new javax.swing.JMenuItem();
        listarProgramasItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salirItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión de Radioemisora");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        OpcMenu.setText("Opciones");

        crearRadioItem.setText("Crear Radioemisora");
        crearRadioItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearRadioItemActionPerformed(evt);
            }
        });
        OpcMenu.add(crearRadioItem);

        locutoresItem.setText("Registrar Locutores");
        locutoresItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locutoresItemActionPerformed(evt);
            }
        });
        OpcMenu.add(locutoresItem);

        programasItem.setText("Registrar Programas");
        programasItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programasItemActionPerformed(evt);
            }
        });
        OpcMenu.add(programasItem);

        discosItem.setText("Registrar Discos");
        discosItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discosItemActionPerformed(evt);
            }
        });
        OpcMenu.add(discosItem);

        playlistItem.setText("Generar Playlist");
        playlistItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playlistItemActionPerformed(evt);
            }
        });
        OpcMenu.add(playlistItem);

        consultasItem.setText("Consultar Cancion por Genero");
        consultasItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultasItemActionPerformed(evt);
            }
        });
        OpcMenu.add(consultasItem);

        listarProgramasItem.setText("Listar Programas");
        listarProgramasItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarProgramasItemActionPerformed(evt);
            }
        });
        OpcMenu.add(listarProgramasItem);
        OpcMenu.add(jSeparator1);

        salirItem.setText("Salir");
        salirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirItemActionPerformed(evt);
            }
        });
        OpcMenu.add(salirItem);

        MenuBar.add(OpcMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 862, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void crearRadioItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearRadioItemActionPerformed
        showPanel("CrearRadio");
    }//GEN-LAST:event_crearRadioItemActionPerformed

    private void locutoresItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locutoresItemActionPerformed
        showPanel("Locutores");
    }//GEN-LAST:event_locutoresItemActionPerformed

    private void programasItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programasItemActionPerformed
        showPanel("Programas");
    }//GEN-LAST:event_programasItemActionPerformed

    private void discosItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discosItemActionPerformed
        showPanel("Discos");
    }//GEN-LAST:event_discosItemActionPerformed

    private void playlistItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playlistItemActionPerformed
        showPanel("Playlist");
    }//GEN-LAST:event_playlistItemActionPerformed

    private void consultasItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultasItemActionPerformed
        showPanel("Consultas");
    }//GEN-LAST:event_consultasItemActionPerformed

    private void listarProgramasItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarProgramasItemActionPerformed
        showPanel("ListarProgramas");
    }//GEN-LAST:event_listarProgramasItemActionPerformed

    private void salirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirItemActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu OpcMenu;
    private javax.swing.JMenuItem consultasItem;
    private javax.swing.JMenuItem crearRadioItem;
    private javax.swing.JMenuItem discosItem;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem listarProgramasItem;
    private javax.swing.JMenuItem locutoresItem;
    private javax.swing.JMenuItem playlistItem;
    private javax.swing.JMenuItem programasItem;
    private javax.swing.JMenuItem salirItem;
    // End of variables declaration//GEN-END:variables
}
