/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package radioemisor;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author tonyc
 */
public class tester extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(tester.class.getName());
    
    private RadioEmisor radio;
    private JPanel cardPanel;
    private CardLayout cardLayout;
    
    // Paneles
    
    /**
     * Creates new form tester
     */
    public tester() {
        radio = new RadioEmisor("", 0, "");
        
        
        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);
        
        
        
                // Configurar layout principal
        setLayout(new BorderLayout());
        add(cardPanel, BorderLayout.CENTER);
        
        initComponents();
    }
    
    public final void showPanel(String panelName) {
        cardLayout.show(cardPanel, panelName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menutbp = new javax.swing.JTabbedPane();
        CrearRdpnl = new javax.swing.JPanel();
        CrearRdlbl = new javax.swing.JLabel();
        RdNombretxf = new javax.swing.JTextField();
        RdFrecuenciatxf = new javax.swing.JTextField();
        RdDirecctxf = new javax.swing.JTextField();
        RdNamelbl = new javax.swing.JLabel();
        RdFreqlbl = new javax.swing.JLabel();
        RdDirecclbl = new javax.swing.JLabel();
        CrearRdbtn = new javax.swing.JButton();
        RegLocpnl = new javax.swing.JPanel();
        LocMaillbl = new javax.swing.JLabel();
        LocTellbl = new javax.swing.JLabel();
        AgregLocbtn = new javax.swing.JButton();
        RegLoclbl = new javax.swing.JLabel();
        LocNametxf = new javax.swing.JTextField();
        LocMailtxf = new javax.swing.JTextField();
        LocTeltxf = new javax.swing.JTextField();
        LocNamelbl = new javax.swing.JLabel();
        LocIDlbl = new javax.swing.JLabel();
        LocIDtxf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Loctxa = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        RegPgrpnl = new javax.swing.JPanel();
        Duraclbl = new javax.swing.JLabel();
        Genlbl = new javax.swing.JLabel();
        AgregPgrbtn = new javax.swing.JButton();
        RegLoclbl1 = new javax.swing.JLabel();
        Horatxf = new javax.swing.JTextField();
        Duractxf = new javax.swing.JTextField();
        Gentxf = new javax.swing.JTextField();
        Horalbl = new javax.swing.JLabel();
        PgrNamelbl = new javax.swing.JLabel();
        PgrNametxf = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Pgrtxa = new javax.swing.JTextArea();
        PgrLoclbl = new javax.swing.JLabel();
        PgrLoccbx = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menutbp.setBackground(new java.awt.Color(255, 255, 255));
        Menutbp.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        CrearRdlbl.setBackground(new java.awt.Color(102, 102, 0));
        CrearRdlbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        CrearRdlbl.setText("Crear Radioemisora");

        RdNombretxf.setOpaque(true);

        RdFrecuenciatxf.setOpaque(true);
        RdFrecuenciatxf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdFrecuenciatxfActionPerformed(evt);
            }
        });

        RdDirecctxf.setOpaque(true);

        RdNamelbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        RdNamelbl.setText("Nombre:");

        RdFreqlbl.setFont(RdFreqlbl.getFont().deriveFont(RdFreqlbl.getFont().getSize()+2f));
        RdFreqlbl.setText("Frecuencia:");

        RdDirecclbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        RdDirecclbl.setText("Direccion Web:");

        CrearRdbtn.setBackground(new java.awt.Color(204, 255, 255));
        CrearRdbtn.setText("Crear Radioemisora");
        CrearRdbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CrearRdbtn.setOpaque(true);
        CrearRdbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearRdbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CrearRdpnlLayout = new javax.swing.GroupLayout(CrearRdpnl);
        CrearRdpnl.setLayout(CrearRdpnlLayout);
        CrearRdpnlLayout.setHorizontalGroup(
            CrearRdpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearRdpnlLayout.createSequentialGroup()
                .addGroup(CrearRdpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearRdpnlLayout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(RdNombretxf, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CrearRdpnlLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(CrearRdpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CrearRdpnlLayout.createSequentialGroup()
                                .addGroup(CrearRdpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RdNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RdFreqlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RdDirecclbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(CrearRdpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RdDirecctxf, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RdFrecuenciatxf, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CrearRdpnlLayout.createSequentialGroup()
                                .addGroup(CrearRdpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CrearRdbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CrearRdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        CrearRdpnlLayout.setVerticalGroup(
            CrearRdpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearRdpnlLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(CrearRdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(CrearRdpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RdNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RdNombretxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CrearRdpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RdFrecuenciatxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RdFreqlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CrearRdpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RdDirecctxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RdDirecclbl))
                .addGap(18, 18, 18)
                .addComponent(CrearRdbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        Menutbp.addTab("tab1", CrearRdpnl);

        LocMaillbl.setFont(LocMaillbl.getFont().deriveFont(LocMaillbl.getFont().getSize()+2f));
        LocMaillbl.setText("Correo:");

        LocTellbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        LocTellbl.setText("Telefono:");

        AgregLocbtn.setBackground(new java.awt.Color(204, 255, 255));
        AgregLocbtn.setText("Agregar Locutor");
        AgregLocbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        AgregLocbtn.setOpaque(true);
        AgregLocbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregLocbtnActionPerformed(evt);
            }
        });

        RegLoclbl.setBackground(new java.awt.Color(102, 102, 0));
        RegLoclbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        RegLoclbl.setText("Registrar Locutores");

        LocNametxf.setOpaque(true);

        LocMailtxf.setOpaque(true);
        LocMailtxf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocMailtxfActionPerformed(evt);
            }
        });

        LocTeltxf.setOpaque(true);

        LocNamelbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        LocNamelbl.setText("Nombre:");

        LocIDlbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        LocIDlbl.setText("ID:");

        LocIDtxf.setOpaque(true);

        Loctxa.setColumns(20);
        Loctxa.setRows(5);
        jScrollPane1.setViewportView(Loctxa);

        javax.swing.GroupLayout RegLocpnlLayout = new javax.swing.GroupLayout(RegLocpnl);
        RegLocpnl.setLayout(RegLocpnlLayout);
        RegLocpnlLayout.setHorizontalGroup(
            RegLocpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegLocpnlLayout.createSequentialGroup()
                .addGroup(RegLocpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegLocpnlLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(RegLocpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegLoclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RegLocpnlLayout.createSequentialGroup()
                                .addGroup(RegLocpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LocTellbl)
                                    .addComponent(LocNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LocMaillbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LocIDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(RegLocpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LocIDtxf, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LocMailtxf, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LocNametxf, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LocTeltxf, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 316, Short.MAX_VALUE))
                    .addGroup(RegLocpnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(RegLocpnlLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(AgregLocbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegLocpnlLayout.setVerticalGroup(
            RegLocpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegLocpnlLayout.createSequentialGroup()
                .addComponent(RegLoclbl)
                .addGap(1, 1, 1)
                .addGroup(RegLocpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocIDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocIDtxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegLocpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocNametxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegLocpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LocMailtxf)
                    .addComponent(LocMaillbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegLocpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocTeltxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocTellbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AgregLocbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        Menutbp.addTab("tab2", RegLocpnl);

        Duraclbl.setFont(Duraclbl.getFont().deriveFont(Duraclbl.getFont().getSize()+2f));
        Duraclbl.setText("Duracion (min):");

        Genlbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        Genlbl.setText("Genero:");

        AgregPgrbtn.setBackground(new java.awt.Color(204, 255, 255));
        AgregPgrbtn.setText("Agregar Programa");
        AgregPgrbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        AgregPgrbtn.setOpaque(true);
        AgregPgrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregPgrbtnActionPerformed(evt);
            }
        });

        RegLoclbl1.setBackground(new java.awt.Color(102, 102, 0));
        RegLoclbl1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        RegLoclbl1.setText("Registrar Programas");

        Horatxf.setOpaque(true);

        Duractxf.setOpaque(true);
        Duractxf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuractxfActionPerformed(evt);
            }
        });

        Gentxf.setOpaque(true);

        Horalbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        Horalbl.setText("Horario (HH:MM)");

        PgrNamelbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        PgrNamelbl.setText("Nombre:");

        PgrNametxf.setOpaque(true);

        Pgrtxa.setColumns(20);
        Pgrtxa.setRows(5);
        jScrollPane2.setViewportView(Pgrtxa);

        PgrLoclbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        PgrLoclbl.setText("Locutor:");

        javax.swing.GroupLayout RegPgrpnlLayout = new javax.swing.GroupLayout(RegPgrpnl);
        RegPgrpnl.setLayout(RegPgrpnlLayout);
        RegPgrpnlLayout.setHorizontalGroup(
            RegPgrpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegPgrpnlLayout.createSequentialGroup()
                .addGroup(RegPgrpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegPgrpnlLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(RegPgrpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegLoclbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RegPgrpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(PgrNametxf, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(RegPgrpnlLayout.createSequentialGroup()
                                    .addGroup(RegPgrpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Genlbl)
                                        .addComponent(PgrNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PgrLoclbl)
                                        .addComponent(Horalbl)
                                        .addComponent(Duraclbl))
                                    .addGroup(RegPgrpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(RegPgrpnlLayout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(Horatxf, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegPgrpnlLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(RegPgrpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Gentxf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(PgrLoccbx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addComponent(Duractxf, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(RegPgrpnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(RegPgrpnlLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(AgregPgrbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegPgrpnlLayout.setVerticalGroup(
            RegPgrpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegPgrpnlLayout.createSequentialGroup()
                .addComponent(RegLoclbl1)
                .addGap(1, 1, 1)
                .addGroup(RegPgrpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PgrNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PgrNametxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegPgrpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Horalbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Horatxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegPgrpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Duraclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Duractxf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegPgrpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gentxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Genlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RegPgrpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PgrLoclbl)
                    .addComponent(PgrLoccbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(AgregPgrbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 827, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RegPgrpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RegPgrpnl, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Menutbp.addTab("tab3", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menutbp)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menutbp)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearRdbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearRdbtnActionPerformed
        showPanel("New");
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearRdbtnActionPerformed

    private void RdFrecuenciatxfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdFrecuenciatxfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdFrecuenciatxfActionPerformed

    private void AgregLocbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregLocbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregLocbtnActionPerformed

    private void LocMailtxfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocMailtxfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocMailtxfActionPerformed

    private void AgregPgrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregPgrbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregPgrbtnActionPerformed

    private void DuractxfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuractxfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DuractxfActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(() -> new tester().setVisible(true));
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregLocbtn;
    private javax.swing.JButton AgregPgrbtn;
    private javax.swing.JButton CrearRdbtn;
    private javax.swing.JLabel CrearRdlbl;
    private javax.swing.JPanel CrearRdpnl;
    private javax.swing.JLabel Duraclbl;
    private javax.swing.JTextField Duractxf;
    private javax.swing.JLabel Genlbl;
    private javax.swing.JTextField Gentxf;
    private javax.swing.JLabel Horalbl;
    private javax.swing.JTextField Horatxf;
    private javax.swing.JLabel LocIDlbl;
    private javax.swing.JTextField LocIDtxf;
    private javax.swing.JLabel LocMaillbl;
    private javax.swing.JTextField LocMailtxf;
    private javax.swing.JLabel LocNamelbl;
    private javax.swing.JTextField LocNametxf;
    private javax.swing.JLabel LocTellbl;
    private javax.swing.JTextField LocTeltxf;
    private javax.swing.JTextArea Loctxa;
    private javax.swing.JTabbedPane Menutbp;
    private javax.swing.JComboBox<String> PgrLoccbx;
    private javax.swing.JLabel PgrLoclbl;
    private javax.swing.JLabel PgrNamelbl;
    private javax.swing.JTextField PgrNametxf;
    private javax.swing.JTextArea Pgrtxa;
    private javax.swing.JLabel RdDirecclbl;
    private javax.swing.JTextField RdDirecctxf;
    private javax.swing.JTextField RdFrecuenciatxf;
    private javax.swing.JLabel RdFreqlbl;
    private javax.swing.JLabel RdNamelbl;
    private javax.swing.JTextField RdNombretxf;
    private javax.swing.JLabel RegLoclbl;
    private javax.swing.JLabel RegLoclbl1;
    private javax.swing.JPanel RegLocpnl;
    private javax.swing.JPanel RegPgrpnl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
