/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mi.primer.ventana;

import java.awt.Color;
import java.awt.Point;
import javax.swing.JOptionPane;

/**
 *
 * @author tonyc
 */
public class Mi_ventana1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Mi_ventana1.class.getName());

    /**
     * Creates new form Mi_ventana1
     */
    public Mi_ventana1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaResult = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        cbxop = new javax.swing.JComboBox<>();
        op1lbl = new javax.swing.JLabel();
        op2lbl = new javax.swing.JLabel();
        txfop1 = new javax.swing.JTextField();
        txfop2 = new javax.swing.JTextField();
        oplbl = new javax.swing.JLabel();
        lblerrorop2 = new javax.swing.JLabel();
        lblerrorop1 = new javax.swing.JLabel();
        btnMoveR = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbljugador = new javax.swing.JLabel();
        btnMoveL = new javax.swing.JButton();
        btncalc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Root\n");
        setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setForeground(new java.awt.Color(0, 204, 102));

        txaResult.setColumns(20);
        txaResult.setFont(txaResult.getFont().deriveFont(txaResult.getFont().getSize()+6f));
        txaResult.setRows(5);
        jScrollPane1.setViewportView(txaResult);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setToolTipText("Seleccione la operacion");

        btnadd.setBackground(new java.awt.Color(255, 255, 0));
        btnadd.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        btnadd.setText("Add");
        btnadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnadd.setBorderPainted(false);
        btnadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnaddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnaddMouseExited(evt);
            }
        });
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        cbxop.setBackground(new java.awt.Color(0, 255, 204));
        cbxop.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        cbxop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "×", "÷" }));
        cbxop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxopActionPerformed(evt);
            }
        });

        op1lbl.setBackground(new java.awt.Color(153, 255, 0));
        op1lbl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        op1lbl.setText("Operador 1:");
        op1lbl.setOpaque(true);

        op2lbl.setBackground(new java.awt.Color(153, 255, 0));
        op2lbl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        op2lbl.setText("Operador 2:");
        op2lbl.setOpaque(true);

        txfop1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        txfop1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfop1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfop1KeyTyped(evt);
            }
        });

        txfop2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        txfop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfop2ActionPerformed(evt);
            }
        });
        txfop2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfop2KeyTyped(evt);
            }
        });

        oplbl.setBackground(new java.awt.Color(153, 255, 0));
        oplbl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        oplbl.setText("Operacion");
        oplbl.setOpaque(true);

        lblerrorop2.setBackground(new java.awt.Color(255, 255, 255));
        lblerrorop2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        lblerrorop2.setForeground(new java.awt.Color(255, 0, 51));
        lblerrorop2.setOpaque(true);

        lblerrorop1.setBackground(new java.awt.Color(255, 255, 255));
        lblerrorop1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        lblerrorop1.setForeground(new java.awt.Color(255, 0, 51));
        lblerrorop1.setOpaque(true);

        btnMoveR.setBackground(new java.awt.Color(255, 102, 0));
        btnMoveR.setText(">>");
        btnMoveR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveRActionPerformed(evt);
            }
        });
        btnMoveR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnMoveRKeyPressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51), 3));

        lbljugador.setBackground(new java.awt.Color(102, 255, 204));
        lbljugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbljugador.setText("jugador");
        lbljugador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbljugador.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lbljugador, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lbljugador, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnMoveL.setBackground(new java.awt.Color(255, 102, 0));
        btnMoveL.setText("<<");
        btnMoveL.setActionCommand("<<");
        btnMoveL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveLActionPerformed(evt);
            }
        });

        btncalc.setBackground(new java.awt.Color(255, 255, 0));
        btncalc.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        btncalc.setText("Calcular");
        btncalc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btncalc.setBorderPainted(false);
        btncalc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncalcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncalcMouseExited(evt);
            }
        });
        btncalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btncalc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(oplbl)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(op2lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(op1lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txfop2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(txfop1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblerrorop1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(lblerrorop2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnMoveL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMoveR)
                        .addGap(38, 38, 38))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMoveL)
                            .addComponent(btnMoveR)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(op1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfop1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblerrorop1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(op2lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfop2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblerrorop2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oplbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncalc))))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxopActionPerformed

    private void txfop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfop2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfop2ActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        String valor = JOptionPane.showInputDialog(this, "Que quiere agregar a la bitacora");
        if (valor != null && valor.trim().equals(""))
            txaResult.append(valor + "\n");
        int opcion = JOptionPane.showConfirmDialog(this, "Deseas eliminar", "Confirmacion", JOptionPane.YES_NO_CANCEL_OPTION);
        if (opcion == 0)
            txaResult.setText("");
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnaddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddMouseEntered
        btnadd.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnaddMouseEntered

    private void btnaddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddMouseExited
        btnadd.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnaddMouseExited

    private void txfop1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfop1KeyReleased

    }//GEN-LAST:event_txfop1KeyReleased

    private void txfop1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfop1KeyTyped
        String op1 = txfop1.getText();
        if (!isNumber(op1))
            lblerrorop1.setText("Invalid number");
        else
            lblerrorop1.setText("");
        if (((int)evt.getKeyChar()) == 10)
            txfop1.setText("");
    }//GEN-LAST:event_txfop1KeyTyped

    private void txfop2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfop2KeyTyped
        String op2 = txfop1.getText();
        if (!isNumber(op2)) 
            lblerrorop2.setText("Invalid number");
        else
            lblerrorop2.setText("");
    }//GEN-LAST:event_txfop2KeyTyped

    private void btnMoveRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveRActionPerformed
        Point p = lbljugador.getLocation();
        if (p.x <= 143)
            lbljugador.setLocation(p.x + 5, p.y);
    }//GEN-LAST:event_btnMoveRActionPerformed

    private void btnMoveLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveLActionPerformed
        Point p = lbljugador.getLocation();
        if (p.x > 3)
            lbljugador.setLocation(p.x - 5, p.y);
    }//GEN-LAST:event_btnMoveLActionPerformed

    private void btnMoveRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnMoveRKeyPressed

    }//GEN-LAST:event_btnMoveRKeyPressed

    private void btncalcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncalcMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btncalcMouseEntered

    private void btncalcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncalcMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btncalcMouseExited

    private void btncalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcActionPerformed
                try {
            double value1 = Double.parseDouble(txfop1.getText().trim());
            double value2 = Double.parseDouble(txfop2.getText().trim());
            int cbxidx = cbxop.getSelectedIndex();
            double res = 0;
            String op = "";
            switch (cbxidx) {
                case 0 -> {
                    res = value1 + value2;
                    op = " + ";
                }
                case 1 -> {
                    res = value1 - value2;
                    op = " - ";
                }
                case 2 -> {
                    res = value1 * value2;
                    op = " × ";
                }
                case 3 -> {
                    res = value1 / value2;
                    op = " ÷ ";
                }
            }
            var resstr = Double.toString(res);
            txaResult.append(value1 + op + value2 + " = " + resstr + "\n");
        } catch (NumberFormatException e) {
            txfop1.setText("");
            txfop2.setText("");
            JOptionPane.showMessageDialog(this, "Debe ingresar numeros", "Error!", JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_btncalcActionPerformed

    private boolean isNumber(String str) {
        try{
            double num = Double.parseDouble(str);
            return true;
        } catch (Exception e) {
            return false;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Mi_ventana1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoveL;
    private javax.swing.JButton btnMoveR;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btncalc;
    private javax.swing.JComboBox<String> cbxop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblerrorop1;
    private javax.swing.JLabel lblerrorop2;
    private javax.swing.JLabel lbljugador;
    private javax.swing.JLabel op1lbl;
    private javax.swing.JLabel op2lbl;
    private javax.swing.JLabel oplbl;
    private javax.swing.JTextArea txaResult;
    private javax.swing.JTextField txfop1;
    private javax.swing.JTextField txfop2;
    // End of variables declaration//GEN-END:variables
}
